export enum tableHeader {
  'checkbox' = 'checkbox',
  'code' = 'code',
  'name' = 'name',
  'organizationType' = 'organizationType',
  'classification' = 'classification',
  'headerName' = 'headerName',
  'requestType' = 'requestType',
  'requestStatus' = 'requestStatus',
  'vendorStatus' = 'vendorStatus',
  'status' = 'status',
  'panNumber' = 'panNumber',
  'gstNumber' = 'gstNumber',
  'creditTerms' = 'creditTerms',
  'limitDays' = 'limitDays',
  'viewSummary' = 'viewSummary',
  'edit' = 'edit',
  'toggleButton' = 'toggleButton',
}
